language: python

install:
  - pip install yamllint ansible-lint
  - printf '[defaults]\nroles_path=../' > ansible.cfg

script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - yamllint . -c yamllint.yml
  - ansible-lint

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
